AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Backend API for Managing Game Knight events

  '
Parameters:
  Stage:
    Type: String
    Default: Staging
    Description: API Stage
Resources:
  EventsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Game Knights Events API
      StageName:
        Ref: Stage
      Auth:
        DefaultAuthorizer: CognitoPasswordless
        Authorizers:
          CognitoPasswordless:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:569879156317:userpool/us-east-1_Okkk4SAZX
      Cors: '''*'''
      EndpointConfiguration:
        Type: EDGE
      Tags:
        Owner: EventsAPI
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://cp-sam-deploy-east1/23cb710b406d0755d9583490c407bf9b
      Models:
        NewEvent:
          required:
          - event_type
          - date
          - format
          - game
          - host
          - registered
          type: object
          properties:
            event_type:
              type: string
            date:
              type: string
              format: date
            host:
              type: string
            format:
              type: string
              format: reserved|open
            game:
              type: string
            bgg_id:
              type: integer
              description: BoardGameGeek.com Game ID
            total_spots:
              minimum: 0
              type: integer
            registered:
              type: array
              items:
                type: string
            player_pool:
              items:
                type: string
    Metadata:
      SamResourceId: EventsApiGateway
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: game_events
      AttributeDefinitions:
      - AttributeName: event_id
        AttributeType: S
      - AttributeName: event_type
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      KeySchema:
      - AttributeName: event_id
        KeyType: HASH
      GlobalSecondaryIndexes:
      - IndexName: EventTypeByDate
        KeySchema:
        - AttributeName: event_type
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
      - Key: Name
        Value: game_events
      - Key: Owner
        Value: EventsAPI
    Metadata:
      SamResourceId: EventsTable
  ManageEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cp-sam-deploy-east1/237c2e2d5a84bae4b18cc1cd53c58750
      Handler: app.lambda_handler
      Runtime: python3.12
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: EventsApiGateway
            Path: /event
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        CreateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: EventsApiGateway
            Path: /event
            Method: POST
            Auth:
              Authorizer: CognitoPasswordless
            RequestModel:
              Model: NewEvent
              Required: true
              ValidateBody: false
              ValidateParameters: true
        EventOptions:
          Type: Api
          Properties:
            RestApiId:
              Ref: EventsApiGateway
            Path: /event
            Method: OPTIONS
            Auth:
              Authorizer: NONE
        GetEventRSVP:
          Type: Api
          Properties:
            RestApiId:
              Ref: EventsApiGateway
            Path: /event/rsvp
            Method: GET
            RequestParameters: null
            Auth:
              Authorizer: CognitoPasswordless
        EventRsvpOptions:
          Type: Api
          Properties:
            RestApiId:
              Ref: EventsApiGateway
            Path: /event/rsvp
            Method: OPTIONS
            Auth:
              Authorizer: NONE
      Tags:
        Owner: EventsAPI
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: EventsTable
    Metadata:
      SamResourceId: ManageEventsFunction
Outputs:
  EventsApiGateway:
    Description: API Gateway endpoint URL for Staging stage for Game Knights Events
      function
    Value:
      Fn::Sub: https://${EventsApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/events/
  EventsApiGatewayRestApiId:
    Description: API Gateway ARN for Game Knights Events AWS API Gateway
    Value:
      Ref: EventsApiGateway
    Export:
      Name: EventsApiGateway-RestApiId
  EventsApiGatewayRootResourceId:
    Value:
      Fn::GetAtt:
      - EventsApiGateway
      - RootResourceId
    Export:
      Name: EventsApiGateway-RootResourceId
