version: 0.1
prod:
  build:
    parameters:
      template: ./template.yaml
  deploy:
    parameters:
      region: us-east-1
      stack_name: GameKnightsEventsAPI
      capabilities: CAPABILITY_IAM
      s3_bucket: cp-sam-deploy-east1
      parameter_overrides: "Mode=prod"
dev:
  build:
    parameters:
      template: ./template.yaml
  deploy:
    parameters:
      region: us-east-1
      stack_name: DEVGameKnightsEventsAPI
      capabilities: CAPABILITY_IAM
      s3_bucket: cp-sam-deploy-east1
      parameter_overrides: "Mode=dev"
