AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend API for Managing Game Knight events

Parameters:
  Mode:
    Type: String
    Description: Mode of deployment
    AllowedValues:
      - prod
      - dev

  Stage:
    Type: String
    Default: Staging
    Description: API Stage

  CognitoUserPoolArn:
    Type: String
    Default: arn:aws:cognito-idp:us-east-1:569879156317:userpool/us-east-1_Okkk4SAZX
    Description: Cognito User Pool Arn

Conditions:
  isDev: !Equals [!Ref Mode, dev]

Mappings:
  EnvMap:
    prod:
      CloudFrontS3Bucket: cdkstack-bucket83908e77-7tr0zgs93uwh
      EventsTableName: game_events
      ApiGatewayName: Game Knights Events API
      OwnerTag: EventsAPI
      StackName: GameKnightsEventsAPI
    dev:
      CloudFrontS3Bucket: cdkstack-bucketdevff8a9acd-pine3ubqpres
      EventsTableName: game_events_dev
      ApiGatewayName: Game Knights Events API DEV
      OwnerTag: DevEventsAPI
      StackName: DEVGameKnightsEventsAPI

Resources:
  EventsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !FindInMap [EnvMap, !Ref Mode, ApiGatewayName]
      StageName: !Ref Stage
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*" # allows for logging on any resource
          HttpMethod: "*" # allows for logging on any method
      # Cognito pool auth
      Auth:
        DefaultAuthorizer: CognitoPasswordless
        Authorizers:
          CognitoPasswordless:
            UserPoolArn: !Ref CognitoUserPoolArn
      Cors: "'*'"
      EndpointConfiguration:
        Type: EDGE
      Tags:
        Owner: !FindInMap [EnvMap, !Ref Mode, OwnerTag]
      DefinitionBody:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: "swagger.yaml"
            # Location: s3://cp-sam-deploy-east1/swagger.yaml

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [EnvMap, !Ref Mode, EventsTableName]
      AttributeDefinitions:
        - AttributeName: "event_id"
          AttributeType: "S"
        - AttributeName: "event_type"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "event_id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: EventTypeByDate
          KeySchema:
            - AttributeName: "event_type"
              KeyType: "HASH"
            - AttributeName: "date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Name
          Value: !FindInMap [EnvMap, !Ref Mode, EventsTableName]
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  # API Backend Bucket
  BackendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Mode}-cubes-and-cardboard-backend"
      Tags:
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  RsvpAlertsScheduleGroup:
    Type: AWS::Scheduler::ScheduleGroup
    Properties:
      Name: !Sub rsvp_alerts_${Mode}
      Tags:
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  ReservedRsvpRefreshScheduleGroup:
    Type: AWS::Scheduler::ScheduleGroup
    Properties:
      Name: !Sub reserved_rsvp_refresh_${Mode}
      Tags:
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  ReservedRsvpRefreshScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub reserved_rsvp_refresh_scheduler_role_${Mode}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Description: !Sub Role used by reserved_rsvp_refresh_${Mode} schedules
      Policies:
        - PolicyName: InvokeManageEventsFunction
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action: lambda:InvokeFunction
                Resource: !GetAtt ManageEventsFunction.Arn
                Effect: Allow
      Tags:
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  ManageEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub manage_events_${Mode}
      CodeUri: manage_events/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 30
      Events:
        # /events
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /events
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        EventsOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /events
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /event
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event
            Method: POST
            Auth:
              Authorizer: CognitoPasswordless
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event
            Method: DELETE
            Auth:
              Authorizer: CognitoPasswordless
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event
            Method: PUT
            Auth:
              Authorizer: CognitoPasswordless
        EventOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /players
        GetPlayers:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /players
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        PlayersOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /players
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /player
        CreatePlayer:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /player
            Method: POST
            Auth:
              Authorizer: CognitoPasswordless
        UpdatePlayer:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /player
            Method: PUT
            Auth:
              Authorizer: CognitoPasswordless
        PlayerOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /player
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /player/self
        UpdatePlayerSelf:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /player/self
            Method: PUT
            Auth:
              Authorizer: CognitoPasswordless
        PlayerSelfOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /player/self
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /event/rsvp
        PostEventRSVP:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event/rsvp
            Method: POST
            RequestParameters:
            Auth:
              Authorizer: CognitoPasswordless
        DeleteEventRSVP:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event/rsvp
            Method: DELETE
            RequestParameters:
            Auth:
              Authorizer: CognitoPasswordless
        EventRsvpOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /event/rsvp
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /activitylogs
        GetActivityLogs:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /activitylogs
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        ActivityLogsOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /activitylogs
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /alerts
        GetAlerts:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /alerts
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        AlertsOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /alerts
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # /alerts/player
        GetAlertsPlayer:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /alerts/player
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        PutAlertsPlayer:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /alerts/player
            Method: PUT
            Auth:
              Authorizer: CognitoPasswordless
        AlertsPlayerOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /alerts/player
            Method: OPTIONS
            Auth:
              Authorizer: NONE
      Tags:
        Owner: !FindInMap [EnvMap, !Ref Mode, OwnerTag]
      Environment:
        Variables:
          mode: !Ref Mode
          table_name_prod: !If [isDev, !ImportValue EventsTable-prod-GameKnightsEventsAPI, ""]
          table_name: !FindInMap [EnvMap, !Ref Mode, EventsTableName]
          s3_bucket: !FindInMap [EnvMap, !Ref Mode, CloudFrontS3Bucket]
          rsvp_sqs_url: !Ref RsvpAlertSqsQueue
          sns_topic: !Ref BggPictureSnsTopic
          backend_bucket: !Ref BackendBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
        - !If
          - isDev
          - DynamoDBReadPolicy:
              TableName: !ImportValue EventsTable-prod-GameKnightsEventsAPI
          - !Ref "AWS::NoValue"
        - SQSSendMessagePolicy:
            QueueName: !GetAtt RsvpAlertSqsQueue.QueueName
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvMap, !Ref Mode, CloudFrontS3Bucket]
        - S3CrudPolicy:
            BucketName: !Ref BackendBucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt BggPictureSnsTopic.TopicName
          # Allow cognito pool ListUsers
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ListUsers
                - cognito-idp:ListUsersInGroup
                - cognito-idp:ListGroups
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminAddUserToGroup
                - cognito-idp:AdminRemoveUserFromGroup
                - cognito-idp:AdminUpdateUserAttributes
                - cognito-idp:AdminDeleteUserAttributes
              Resource: !Ref CognitoUserPoolArn
        - Statement:
            - Effect: Allow
              Action:
                - logs:StartQuery
                - logs:StopQuery
                - logs:GetQueryResults
              Resource:
                - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/manage_events_${Mode}:*"
                - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/manage_events_${Mode}:log-stream:*"
        - Statement:
            - Effect: Allow
              Action:
                - scheduler:GetSchedule
                - scheduler:UpdateSchedule
                - iam:PassRole
              Resource:
                - !Sub "arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/${RsvpAlertsScheduleGroup}/rsvp_alerts_schedule_${Mode}"
                - !GetAtt RsvpAlertsFunctionScheduleEventRole.Arn
  ManageEventsFunctionRoleScheduleEventPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: ReservedRsvpRefresh
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - scheduler:GetSchedule
              - scheduler:UpdateSchedule
              - scheduler:CreateSchedule
              - scheduler:DeleteSchedule
              - iam:PassRole
            Resource:
              - !Sub "arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/${ReservedRsvpRefreshScheduleGroup}/*"
              - !GetAtt ReservedRsvpRefreshScheduleRole.Arn
      Roles:
        - !Ref ManageEventsFunctionRole

  BggSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "BggSearch_${Mode}"
      CodeUri: bgg_search/
      Handler: bgg_search.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 30
      Events:
        GameSearch:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /gamesearch
            Method: GET
            Auth:
              Authorizer: CognitoPasswordless
        GameSearchOptions:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /gamesearch
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  RsvpAlertsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "rsvp_alerts_${Mode}"
      CodeUri: rsvp_alerts_ts/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          MODE: !Ref Mode
          RSVP_SQS_URL: !Ref RsvpAlertSqsQueue
          S3_BUCKET: !FindInMap [EnvMap, !Ref Mode, CloudFrontS3Bucket]
          TABLE_NAME: !FindInMap [EnvMap, !Ref Mode, EventsTableName]
          BACKEND_BUCKET: !Ref BackendBucket
          NODE_OPTIONS: --enable-source-maps
      Events:
        ScheduleEvent:
          # Initial Scheduled event placeholder (modified by the 'manage_events' lambda after each RSVP change)
          Type: ScheduleV2
          Properties:
            Name: !Sub "rsvp_alerts_schedule_${Mode}"
            GroupName: !Ref RsvpAlertsScheduleGroup
            ScheduleExpression: "at(2024-04-02T03:59:00)"
            State: DISABLED
      Policies:
        - SESCrudPolicy:
            IdentityName: cubesandcardboard.net
        - SQSPollerPolicy:
            QueueName: !GetAtt RsvpAlertSqsQueue.QueueName
        - S3ReadPolicy:
            BucketName: !FindInMap [EnvMap, !Ref Mode, CloudFrontS3Bucket]
        - S3ReadPolicy:
            BucketName: !Ref BackendBucket
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
      Tags:
        Owner: !FindInMap [EnvMap, !Ref Mode, OwnerTag]
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - emitter

  RetrieveBGGImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "RetrieveBGGImage_${Mode}"
      CodeUri: bgg_picture/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 30
      Events:
        MySNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref BggPictureSnsTopic
      Policies:
        - S3ReadPolicy:
            BucketName: !FindInMap [EnvMap, !Ref Mode, CloudFrontS3Bucket]
        - S3WritePolicy:
            BucketName: !FindInMap [EnvMap, !Ref Mode, CloudFrontS3Bucket]

      Tags:
        Owner: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  BggPictureSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "BggPictureSnsTopic_${Mode}"
      Tags:
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

  RsvpAlertSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      QueueName: !Sub "sqs_rsvp_alerts_${Mode}.fifo"
      FifoQueue: true
      VisibilityTimeout: 700
      Tags:
        - Key: Owner
          Value: !FindInMap [EnvMap, !Ref Mode, OwnerTag]

Outputs:
  EventsApiGateway:
    Description: "API Gateway endpoint URL for Staging stage for Game Knights Events function"
    Value: !Sub "https://${EventsApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  EventsApiGatewayRestApiId:
    Description: "API Gateway ARN for Game Knights Events AWS API Gateway"
    Value: !Ref EventsApiGateway
    Export:
      Name: !Sub "EventsApiGateway-RestApiId-${Mode}"
  EventsApiGatewayRootResourceId:
    Value: !GetAtt EventsApiGateway.RootResourceId
    Export:
      Name: !Sub "EventsApiGateway-RootResourceId-${Mode}"
  RsvpSQSUrl:
    Value: !Ref RsvpAlertSqsQueue
  SNSTopic:
    Value: !Ref BggPictureSnsTopic
  BackendBucket:
    Value: !Ref BackendBucket
  EventsTable:
    Value: !Ref EventsTable
    Export:
      Name: !Sub "EventsTable-${Mode}-${AWS::StackName}"
  RsvpAlertsFunctionScheduleEventRoleArn:
    Value: !GetAtt RsvpAlertsFunctionScheduleEventRole.Arn
  ReservedRsvpRefreshScheduleRole:
    Value: !GetAtt ReservedRsvpRefreshScheduleRole.Arn
